FROM ubuntu:24.04

# Install dependencies
RUN apt update && apt install -y \
    iproute2 iw wireless-tools \
    hostapd wpasupplicant \
    net-tools \
    dnsmasq iptables \
    isc-dhcp-client \
    iputils-ping \
    procps kmod sudo

# Enable dbus (needed for wpa_supplicant)
RUN mkdir -p /var/run/dbus && chmod 755 /var/run/dbus

# Expose ports if needed (for DHCP, DNS, or external connections)
EXPOSE 67/UDP 68/UDP 53/UDP 80/TCP

